FROM node:20-alpine

LABEL maintainer="SouJunior Backend Team"

WORKDIR /usr/app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]